### ISSUE TITLE
convertToMSnset does not accept metadata as tibble

### ISSUE THREAD

**Issue by eldrid01** [crukci-bioinformatics/qPLEXanalyzer#12]
The error is the result of the call to set the phenotypic data on the newly created MSnSet object and is as follows:
Error in validObject(object) : 
  invalid class “MSnSet” object: 1: sampleNames differ between assayData and phenoData
invalid class “MSnSet” object: 2: sampleNames differ between phenoData and protocolData

Perhaps we should check if the sample metadata passed in is a tibble and if so convert it to a dataframe.

Also there is a warning from earlier on in the function where we set the row names on the metadata due to this being deprecated for tibbles.

**Comment by AshKernow** [comment]
The problem was that the function attempts to add row names to the meta data. If the metadata object is a tibble, it cannot do this (leads to the warnings). The merge into the MSnSet object then doesn't work as it is looking for the sample names as row names (errors).

Fixed. 

The function already checks that the object has the attribute 'data.frame' - this is true for tibbles. The function now applies 'as.data.frame' to the object prior to adding the row names.
