### ISSUE TITLE
maVolPlot bug

### ISSUE THREAD

**Issue by chilamakuricsreddy** [crukci-bioinformatics/qPLEXanalyzer#13]
- wanted to show significant and selected genes are identical
- Selected significant and genes to show using same fdrCutOff and lfcCutOff, but the MA and volcano plots the selected and significant genes dose not agree. 

adj_p_cut_off <- 0.01
fc_cut_off <- 1

gene_to_show <- filter( diffexp, adj.P.Val < adj_p_cut_off & (log2FC > fc_cut_off | log2FC < -fc_cut_off  )) %>% 
  select(GeneSymbol) %>% 
  pull(GeneSymbol)

# MA plot
maVolPlot(diffstats, contrast = contrasts, plotType="MA", 
          title= contrasts, 
          fdrCutOff=adj_p_cut_off,
          lfcCutOff= fc_cut_off, 
          selectedGenes=gene_to_show
            )

# Volcano plot
maVolPlot(diffstats, contrast = contrasts, plotType="Volcano", 
          title= contrasts, 
          fdrCutOff=adj_p_cut_off,
          lfcCutOff= fc_cut_off, 
          selectedGenes=gene_to_show
   )

**Comment by AshKernow** [comment]
The problem was down to the fact that the function uses the GeneSymbol to identify the data rows that pertain to "selectedGenes". In this case one of the selected genes did not have GeneSymbol, so in the "gene_to_show" vector, it was `NA`. This then matched 12 other rows of the data. This could also occur if two Accessions are annotated with the same Gene symbol. 

Fixed

I have updated the function so that it accepts Accessions instead of Gene Symbols.
